/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg431;

import java.util.Arrays;
import javax.swing.*;

/**
 *
 * @author Garrett
 */
public class TerminalSelection extends javax.swing.JPanel {

    /**
     * Creates new form TerminalSelection
     */
    public TerminalSelection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProviderButton = new javax.swing.JButton();
        PizzaAnonymousButton = new javax.swing.JButton();
        SelectionLabel = new javax.swing.JLabel();

        ProviderButton.setText("Provider Terminal");
        ProviderButton.setMaximumSize(new java.awt.Dimension(159, 23));
        ProviderButton.setMinimumSize(new java.awt.Dimension(159, 23));
        ProviderButton.setPreferredSize(new java.awt.Dimension(159, 23));
        ProviderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProviderButtonActionPerformed(evt);
            }
        });

        PizzaAnonymousButton.setText("Pizza Anonymous Terminal");
        PizzaAnonymousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PizzaAnonymousButtonActionPerformed(evt);
            }
        });

        SelectionLabel.setText("Select a terminal to use:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(PizzaAnonymousButton)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(SelectionLabel)
                            .addGap(19, 19, 19)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(ProviderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(SelectionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProviderButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PizzaAnonymousButton)
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ProviderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProviderButtonActionPerformed
        String input = JOptionPane.showInputDialog(this, "Enter Provider ID:");
        try {
            if (ProviderList.instance().validate(Integer.parseInt(input))) {
                // TODO Happy path
            } else {
                JOptionPane.showMessageDialog(null, "Provider does not exist");
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_ProviderButtonActionPerformed

    private void PizzaAnonymousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PizzaAnonymousButtonActionPerformed
        String pass = this.getPassword("Enter Admin password:");
        if (pass != null) {
            if (Security.validateAdmin(pass)) {
                // TODO happy path
            } else {
                JOptionPane.showMessageDialog(null, "Wrong Password");
            }
        }
    }//GEN-LAST:event_PizzaAnonymousButtonActionPerformed

    private String getPassword(String prompt) {
        String result = null;
        JPanel panel = new JPanel();
        JLabel label = new JLabel(prompt);
        JPasswordField pass = new JPasswordField(10);
        panel.add(label);
        panel.add(pass);
        String[] options = new String[]{"OK", "Cancel"};
        int option = JOptionPane.showOptionDialog(null, panel, prompt,
                JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                null, options, options[1]);
        if (option == 0) // pressing OK button
        {
            char[] password = pass.getPassword();

            result = new String(password);
            System.out.println(result);

        }

        return result;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PizzaAnonymousButton;
    private javax.swing.JButton ProviderButton;
    private javax.swing.JLabel SelectionLabel;
    // End of variables declaration//GEN-END:variables
}
